version: "3.9"
services:
  database:
    image: database:production
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: administration
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      WINGMAN_SERVICE_PASSWORD: ${WINGMAN_SERVICE_PASSWORD}
      SHOPIFY_INSTALLER_SERVICE_PASSWORD: ${SHOPIFY_INSTALLER_SERVICE_PASSWORD}
    networks:
      - proxynet
volumes:
  pgdata:
networks:
  proxynet:
    name: ozia_backend
